'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;div id=&quot;js-importwizard&quot; class=&quot;iWizWrapper&quot;&gt;
        '''					&lt;section id=&quot;js-importWizardForm rel=&quot; redactor-form-tag&quot;=&quot;&quot;&gt;
        '''
        '''						&lt;div class=&quot;ccWizardHeader&quot;&gt;Import Wizard&lt;/div&gt;
        '''						&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot; class=&quot;ccWizardPanel&quot;&gt;
        '''							&lt;div&gt;&lt;strong&gt;Select the destination for your data&lt;/strong&gt;&lt;br&gt;&lt;br&gt;&lt;p&gt;For example, to import a list in to people, select People.&lt;/p&gt;
        '''							&lt;/div&gt;
        '''							&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; heig [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Importwizard2layout() As String
            Get
                Return ResourceManager.GetString("Importwizard2layout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                     &lt;div id=&quot;js-importwizard&quot; class=&quot;iWizWrapper&quot; &gt;
        '''					&lt;form id=&quot;js-importWizardForm&gt;
        '''					&lt;td valign=&quot;top&quot;&gt;
        '''						&lt;div class=&quot;ccWizardHeader&quot;&gt;Import Wizard&lt;/div&gt;
        '''						&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot; class=&quot;ccWizardPanel&quot;&gt;
        '''							&lt;div&gt;&lt;b&gt;Upload your File&lt;/b&gt;&lt;br&gt;&lt;br&gt;Hit browse to locate the file you want to upload...
        '''							&lt;/div&gt;
        '''							&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; height=&quot;100&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ImportwizardLayout() As String
            Get
                Return ResourceManager.GetString("ImportwizardLayout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                   &lt;div id=&quot;js-importwizard&quot; class=&quot;iWizWrapper&quot;&gt;		
        '''					   &lt;form id=&quot;js-importWizardForm&quot;&gt;									   
        '''					  &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;500&quot; align=&quot;center&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot;&gt;
        '''						&lt;div class=&quot;ccWizardHeader&quot;&gt;Import Wizard&lt;/div&gt;
        '''						&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot; class=&quot;ccWizardPanel&quot;&gt;
        '''							&lt;div&gt;&lt;b&gt;Select the import source&lt;/b&gt;&lt;br&gt;&lt;br&gt;There are several sources you can use for your da [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property importWizardSelectLayout() As String
            Get
                Return ResourceManager.GetString("importWizardSelectLayout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select top 1 m.name as personName, o.organizationName 
        '''from ccmembers m left join organizations o on o.id=m.organizationId
        '''where o.id={0}.
        '''</summary>
        Friend ReadOnly Property sampleSql() As String
            Get
                Return ResourceManager.GetString("sampleSql", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
