<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>aoImportWizard</AssemblyName>
    <LangVersion>latest</LangVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>key1.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contensive.CPBaseClass" Version="26.3.10.15" />
    <PackageReference Include="Contensive.DbModels" Version="26.3.10.15" />
    <PackageReference Include="System.Text.Json" Version="9.0.5" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Importwizard2layout.txt" />
    <Content Include="Resources\ImportwizardLayout.txt" />
    <Content Include="Resources\importWizardSelectLayout.txt" />
    <Content Include="Resources\sampleSql.txt" />
  </ItemGroup>
</Project>
