// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using Microsoft.VisualBasic;

namespace My.Resources {

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [HideModuleName()]
    internal static class Resources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    var temp = new System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to &lt;div id=&quot;js-importwizard&quot; class=&quot;iWizWrapper&quot;&gt;
        /// 					&lt;section id=&quot;js-importWizardForm rel=&quot; redactor-form-tag&quot;=&quot;&quot;&gt;
        /// 
        /// 						&lt;div class=&quot;ccWizardHeader&quot;&gt;Import Wizard&lt;/div&gt;
        /// 						&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot; class=&quot;ccWizardPanel&quot;&gt;
        /// 							&lt;div&gt;&lt;strong&gt;Select the destination for your data&lt;/strong&gt;&lt;br&gt;&lt;br&gt;&lt;p&gt;For example, to import a list in to people, select People.&lt;/p&gt;
        /// 							&lt;/div&gt;
        /// 							&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; heig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Importwizard2layout {
            get {
                return ResourceManager.GetString("Importwizard2layout", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to                     &lt;div id=&quot;js-importwizard&quot; class=&quot;iWizWrapper&quot; &gt;
        /// 					&lt;form id=&quot;js-importWizardForm&gt;
        /// 					&lt;td valign=&quot;top&quot;&gt;
        /// 						&lt;div class=&quot;ccWizardHeader&quot;&gt;Import Wizard&lt;/div&gt;
        /// 						&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot; class=&quot;ccWizardPanel&quot;&gt;
        /// 							&lt;div&gt;&lt;b&gt;Upload your File&lt;/b&gt;&lt;br&gt;&lt;br&gt;Hit browse to locate the file you want to upload...
        /// 							&lt;/div&gt;
        /// 							&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; height=&quot;100&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportwizardLayout {
            get {
                return ResourceManager.GetString("ImportwizardLayout", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to                   &lt;div id=&quot;js-importwizard&quot; class=&quot;iWizWrapper&quot;&gt;		
        /// 					   &lt;form id=&quot;js-importWizardForm&quot;&gt;									   
        /// 					  &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;500&quot; align=&quot;center&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot;&gt;
        /// 						&lt;div class=&quot;ccWizardHeader&quot;&gt;Import Wizard&lt;/div&gt;
        /// 						&lt;table border=&quot;0&quot; cellpadding=&quot;10&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td valign=&quot;top&quot; class=&quot;ccWizardPanel&quot;&gt;
        /// 							&lt;div&gt;&lt;b&gt;Select the import source&lt;/b&gt;&lt;br&gt;&lt;br&gt;There are several sources you can use for your da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string importWizardSelectLayout {
            get {
                return ResourceManager.GetString("importWizardSelectLayout", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to select top 1 m.name as personName, o.organizationName 
        /// from ccmembers m left join organizations o on o.id=m.organizationId
        /// where o.id={0}.
        /// </summary>
        internal static string sampleSql {
            get {
                return ResourceManager.GetString("sampleSql", resourceCulture);
            }
        }
    }
}